### ISSUE TITLE
[Bug]: Deploying a built container on Leda / kanto-cm with databroker (without dapr)

### ISSUE THREAD

**Issue by chheis** [eclipse-velocitas/vehicle-app-cpp-sdk#59]
### What happened?

While deploying a sample application, I have observed that the ENV variables are differently used, with no clear naming.
e.g.: DAPR_GRPC_PORT => needs to be set to the databroker grpc port while using a "native" integration like in python SDK.
So it is very inconvenience that there is currently a different deployment json needed with different ENV parameters when switching between python and C++.
https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/blob/e06002292cfc3fd6209d707d56323500a3775083/sdk/src/sdk/grpc/VehicleDataBrokerClient.cpp#L56

### Operating System

Other

### What release version or branch did you use?

https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/blob/e06002292cfc3fd6209d707d56323500a3775083/sdk/src/sdk/grpc/VehicleDataBrokerClient.cpp#L56

### Relevant log output

```shell
Connection error with grpc
```

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by chheis** [comment]
@doosuu: @MP91 has seen this behaviour already

**Comment by MP91** [comment]
Hey @chheis, @BjoernAtBosch  is already working on a fix

**Comment by MP91** [comment]
@BjoernAtBosch isn't that already done? you adapted the environment variables or? Could you link the PR and close this?

**Comment by BjoernAtBosch** [comment]
Fixed with these versions:
https://github.com/eclipse-velocitas/devenv-runtimes/releases/tag/v1.0.3
https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/releases/tag/v0.3.3
https://github.com/eclipse-velocitas/vehicle-app-cpp-template/commit/6f5705dba31f1c52fea20a96cb7401ec97eadf95

See [SDK's README](https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/blob/v0.3.3/README.md).

Corresponding PRs:
https://github.com/eclipse-velocitas/devenv-runtimes/pull/22
https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/pull/62
https://github.com/eclipse-velocitas/vehicle-app-cpp-template/pull/56
