### ISSUE TITLE
[Bug]: Logger fails on json-string

### ISSUE THREAD

**Issue by MP91** [eclipse-velocitas/vehicle-app-cpp-sdk#92]
### Severity

High

### What release version, tag or commit-hash did you use?

v0.5.1

### Current Behavior

```cpp
void SampleApp::onSetPositionRequestReceived(const std::string& data) {
    const auto logMessage = fmt::format("position request: \"{}\"", data);
    velocitas::logger().debug(logMessage);
}
```
When subscribing to a datapoint like in the seatadjuster-example, we have to provide a callback like the one above. The data in this case is some json-string with the needed data. Unfortunately this code leeds to an error: `Callback threw an exception on update: invalid format string `

Whereas the following code just works fine:
```cpp
void SampleApp::onSetPositionRequestReceived(const std::string& data) {
    velocitas::logger().debug("position request: \"{}\"", data);
}
```

### Steps to Reproduce

1. adapt the code accordingly
1. build and start the app
2. send some json request
3. onError-callback is called

### Expected Behavior

app should not fail

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by erikbosch** [comment]
Strictly speaking I would say that a generating an exception is correct.

In https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/blob/main/sdk/include/sdk/Logger.h#L120 we have 

```
/**
     * @brief Log a message with debug level.
     *
     * @tparam T    Type of the format arguments.
     * @param msg   The format message.
     * @param args  The format arguments.
     */
    template <typename... T> void debug(const std::string& msg, const T&... args) {
        m_impl->debug(fmt::format(msg, args...));
    }
```

So it says first message should be a format message. Even if not explicitly stated here, the format message must follow the [fmt](https://fmt.dev/11.0/) syntax, otherwise you get an error/exception. Here I believe that a JSON string typically do not is a valid fmt format, and in the first example we will actually call format twice.

But I believe we 

But we could off course redesign the API. I think

 template <typename... T> void debug(const std::string& msg, const T&... args) {
        m_impl->debug(fmt::format(msg, args...));
    }

But I believe we could change the API so that if there is no args we will just treat msg as a text string
